### ISSUE TITLE
アップデートした際に発生するエラーについて

### ISSUE THREAD

**Issue by kwkoizumi** [KunihikoKido/sublime-elasticsearch-client#4]
Sublimeの起動時に、パッケージのアップデートが行われた際、
下記のログが出力されて パッケージのコマンドが使用できなくなります。
ご確認よろしくお願いいたします。

```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Packages
state path: /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.469836
first paint time: 0.566563
startup time: 0.582161
lib/dateutil/parser.py in /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages/ElasticsearchClient.sublime-package is not utf-8 encoded, unable to load plugin
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin ElasticsearchClient.ElasticsearchClient
reloading plugin ElasticsearchClient.events
reloading plugin Emmet.emmet-plugin
reloading plugin JsonTree.JsonTree
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
[Errno 2] No such file or directory: 'jq'
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin WordCount.WordCount
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin SublimePythonIDE.__init__
reloading plugin SublimePythonIDE.pep8
reloading plugin SublimePythonIDE.sublime_python
reloading plugin SublimePythonIDE.sublime_python_colors
reloading plugin SublimePythonIDE.sublime_python_commands
reloading plugin SublimePythonIDE.sublime_python_errors
reloading plugin SublimePythonIDE.sublime_python_linting
reloading plugin SublimePythonIDE.sublime_python_refactorings
plugins loaded
Detected ASCII vs Undefined with 100% confidence
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: You have the most recent PyV8 binary
Package Control: Installing 1 upgrades
ignored packages updated to: ["Vintage", "ElasticsearchClient"]
reloading Packages/ElasticsearchClient/Elasticsearch.sublime-settings
unloading plugin ElasticsearchClient.ElasticsearchClient
unloading plugin ElasticsearchClient.events
generating syntax summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded ElasticsearchClient to v2.0.6
ignored packages updated to: ["Vintage"]
lib/dateutil/parser.py in /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages/ElasticsearchClient.sublime-package is not utf-8 encoded, unable to load plugin
reloading Packages/ElasticsearchClient/Elasticsearch.sublime-settings
reloading plugin ElasticsearchClient.ElasticsearchClient
reloading plugin dateutil
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "ElasticsearchClient in /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages/ElasticsearchClient.sublime-package", line 169, in <module>
  File "ElasticsearchClient in /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages/ElasticsearchClient.sublime-package", line 14, in reload_modeule
  File "./imp.py", line 276, in reload
zipimport.ZipImportError: bad local file header in /Users/kwkoizumi/Library/Application Support/Sublime Text 3/Installed Packages/ElasticsearchClient.sublime-package
reloading plugin ElasticsearchClient.events
generating syntax summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Detected ASCII vs Undefined with 100% confidence
Detected ASCII vs Undefined with 100% confidence
Detected UTF-8 vs UTF-8 with 99% confidence
Detected ASCII vs Undefined with 100% confidence
```

**Comment by KunihikoKido** [comment]
.sublime-package 形式の時に問題が発生しているようなので、
パッケージコントロールからインストールした時に、.sublime-package 形式にアーカイブされないように `.no-sublime-package` ファイルを配置しました。 v2.0.7で反映されます。

**Comment by KunihikoKido** [comment]
@kwkoizumi これ直った？

**Comment by kwkoizumi** [comment]
@KunihikoKido さん

アップデートした際に、エラーが発生しないことが確認できました。
ご対応ありがとうございました。
